### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by Bondok6** [melaniesigrid/awesomeBooks#4]
# Hi @JohnFTitor , @melaniesigrid  👋

## Highlight

- Your project is awesome. I love it. 🔥
- Super cool use of CSS, This is the best design I've seen on this project.
- There are no technical errors.

## Suggestions

- It's better to use a semantic element like `<main>` tag instead of `<div class="mainApp">`. It improves SEO as well.
  https://github.com/melaniesigrid/awesomeBooks/blob/6cf71003b419620c5a478ca1f1eb9323c0635e10/index.html#L42

- [Optional] I think it's better to avoid using `alert()` because most modern/common browsers block alerts to prevent alert spamming, and It's not perfect for UI design. I suggest using a popup window or creating a `<span>` with the info.
https://github.com/melaniesigrid/awesomeBooks/blob/8bcd687259a32605acc3ab1c9177cb65e8c69b5a/scripts.js#L58

**Comment by zhadier** [comment]
## Hey Andres and Melanie.
I absolutely loved your code, be it the design or the Javascript logic. I honestly believe it's one of the best codes out there and I had so much to learn. There's nothing to suggest, keep up the good work :)

<img src="https://media1.giphy.com/media/d8D5RoR8adbJaFF3TV/giphy.gif"/>

**Comment by JohnFTitor** [comment]
Thanks for the review guys! Glad to see you liked the project 

We'll implement your suggestions. Thanks again for taking the time to review the code and make it better.

Cheers!

<img src="https://media1.giphy.com/media/Q2DabV4eRh160/giphy.gif"/>
